name:                dictator

ghc-options: -O2 -Wall

dependencies:
  - base >= 4.7 && < 5
  - relude

  - aeson
  - colour
  - containers
  - data-default
  - delay
  - discord-haskell
  - lens
  - MonadRandom
  - normaldistribution
  - palette
  - random
  - scientific
  - text
  - unliftio
  - wreq
  - zip

executable:
  source-dirs: .
  main: Main.hs
