name:                dictator

ghc-options: -O2 -Wall

dependencies:
  - base >= 4.7 && < 5
  - relude

  - aeson
  - bytestring
  - colour
  - containers
  - data-default
  - delay
  - discord-haskell
  - hedis
  - http-client
  - lens
  - MonadRandom
  - normaldistribution
  - palette
  - random-shuffle
  - parsec
  - random
  - scientific
  - text
  - unliftio
  - wreq
  - zip

executable:
  source-dirs: src
  main: Main.hs
